server:
 port: 9099
 servlet:
  context-path: /dts
  
#数据库
spring: 
 datasource:
  url: jdbc:mysql://192.168.1.200:3306/dts?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: 410523
#mybatis
mybatis:
 config-location: classpath:config/mybatis-config.xml
 mapper-locations: classpath:mybatis/**/*.xml